In [61]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
df = pd.read_csv("/Users/siuuuuurya/Desktop/excelfiles/loan_data_for_Random_forest.csv")
pd

In [64]:
df

,Gender,Married,Education,ApplicantIncome,LoanAmount,Loan_Status,Unnamed: 6
0,Male,Yes,Graduate,5000,200,Y,NaN
1,Female,No,Graduate,3000,100,N,NaN
2,Male,Yes,Not Graduate,4000,150,Y,NaN
3,Male,No,Graduate,2000,80,N,NaN
4,Female,Yes,Graduate,2500,120,Y,NaN
5,Female,No,Not Graduate,3500,110,N,NaN
6,Male,Yes,Graduate,6000,250,Y,NaN
7,Male,Yes,Not Graduate,4000,160,Y,NaN
8,Female,No,Graduate,2200,90,N,NaN
9,Male,Yes,Not Graduate,5800,210,Y,NaN
10,Male,No,Graduate,3300,130,Y,NaN
11,Female,Yes,Graduate,2700,100,N,NaN
12,Male,Yes,Not Graduate,3100,170,Y,NaN
13,Female,No,Graduate,2900,95,N,NaN
14,Male,Yes,Graduate,4600,180,Y,NaN
15,Female,No,Not Graduate,3200,115,N,NaN

In [65]:
df.isnull().sum()

Gender              0
Married             0
Education           0
ApplicantIncome     0
LoanAmount          0
Loan_Status         0
Unnamed: 6         16
dtype: int64

In [66]:
df = df.drop(['Unnamed: 6'], axis = 1)

In [67]:
df

    Gender Married     Education  ApplicantIncome  LoanAmount Loan_Status
0     Male     Yes      Graduate             5000         200           Y
1   Female      No      Graduate             3000         100           N
2     Male     Yes  Not Graduate             4000         150           Y
3     Male      No      Graduate             2000          80           N
4   Female     Yes      Graduate             2500         120           Y
5   Female      No  Not Graduate             3500         110           N
6     Male     Yes      Graduate             6000         250           Y
7     Male     Yes  Not Graduate             4000         160           Y
8   Female      No      Graduate             2200          90           N
9     Male     Yes  Not Graduate             5800         210           Y
10    Male      No      Graduate             3300         130           Y
11  Female     Yes      Graduate             2700         100           N
12    Male     Yes  Not Graduate             3100         170           Y
13  Female      No      Graduate             2900          95           N
14    Male     Yes      Graduate             4600         180           Y
15  Female      No  Not Graduate             3200         115           N

In [68]:
df

    Gender Married     Education  ApplicantIncome  LoanAmount Loan_Status
0     Male     Yes      Graduate             5000         200           Y
1   Female      No      Graduate             3000         100           N
2     Male     Yes  Not Graduate             4000         150           Y
3     Male      No      Graduate             2000          80           N
4   Female     Yes      Graduate             2500         120           Y
5   Female      No  Not Graduate             3500         110           N
6     Male     Yes      Graduate             6000         250           Y
7     Male     Yes  Not Graduate             4000         160           Y
8   Female      No      Graduate             2200          90           N
9     Male     Yes  Not Graduate             5800         210           Y
10    Male      No      Graduate             3300         130           Y
11  Female     Yes      Graduate             2700         100           N
12    Male     Yes  Not Graduate             3100         170           Y
13  Female      No      Graduate             2900          95           N
14    Male     Yes      Graduate             4600         180           Y
15  Female      No  Not Graduate             3200         115           N

In [69]:
encoded1 = LabelEncoder()
encoded2 = LabelEncoder()
df['Gender_encoded'] = encoded.fit_transform(df['Gender'])
df['Married_encoded'] = encoded.fit_transform(df['Married'])

In [70]:
encoded3 = LabelEncoder()
df['Encoded_Education'] = encoded.fit_transform(df['Education'])

In [83]:
df = df.drop(['Gender','Education','Married'], axis = 1)

KeyError: "['Gender', 'Education', 'Married'] not found in axis"

In [84]:
df

,ApplicantIncome,LoanAmount,Loan_Status,Gender_encoded,Married_encoded,Encoded_Education
0,5000,200,Y,1,1,0
1,3000,100,N,0,0,0
2,4000,150,Y,1,1,1
3,2000,80,N,1,0,0
4,2500,120,Y,0,1,0
5,3500,110,N,0,0,1
6,6000,250,Y,1,1,0
7,4000,160,Y,1,1,1
8,2200,90,N,0,0,0
9,5800,210,Y,1,1,1
10,3300,130,Y,1,0,0
11,2700,100,N,0,1,0
12,3100,170,Y,1,1,1
13,2900,95,N,0,0,0
14,4600,180,Y,1,1,0
15,3200,115,N,0,0,1

In [85]:
X = df.drop('Loan_status_encoded', axis = 1)

KeyError: "['Loan_status_encoded'] not found in axis"

In [49]:
Y = df.Loan_status_encoded

In [50]:
X

,ApplicantIncome,LoanAmount,Gender_encoded,Married_encoded,Encoded_Education
0,5000,200,1,1,0
1,3000,100,0,0,0
2,4000,150,1,1,1
3,2000,80,1,0,0
4,2500,120,0,1,0
5,3500,110,0,0,1
6,6000,250,1,1,0
7,4000,160,1,1,1
8,2200,90,0,0,0
9,5800,210,1,1,1
10,3300,130,1,0,0
11,2700,100,0,1,0
12,3100,170,1,1,1
13,2900,95,0,0,0
14,4600,180,1,1,0
15,3200,115,0,0,1

In [51]:
Y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     1
8     0
9     1
10    1
11    0
12    1
13    0
14    1
15    0
Name: Loan_status_encoded, dtype: int64

# Model decleration

In [ ]:
Model = RandomForestClassifier(n_estimators = 100, random_state = 42)

In [74]:
x_train , x_test , y_train , y_test = train_test_split( X , Y, test_size=0.2 )

In [75]:
X

,ApplicantIncome,LoanAmount,Gender_encoded,Married_encoded,Encoded_Education
0,5000,200,1,1,0
1,3000,100,0,0,0
2,4000,150,1,1,1
3,2000,80,1,0,0
4,2500,120,0,1,0
5,3500,110,0,0,1
6,6000,250,1,1,0
7,4000,160,1,1,1
8,2200,90,0,0,0
9,5800,210,1,1,1
10,3300,130,1,0,0
11,2700,100,0,1,0
12,3100,170,1,1,1
13,2900,95,0,0,0
14,4600,180,1,1,0
15,3200,115,0,0,1

In [76]:
Y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     1
8     0
9     1
10    1
11    0
12    1
13    0
14    1
15    0
Name: Loan_status_encoded, dtype: int64

In [77]:
df

,ApplicantIncome,LoanAmount,Loan_Status,Gender_encoded,Married_encoded,Encoded_Education
0,5000,200,Y,1,1,0
1,3000,100,N,0,0,0
2,4000,150,Y,1,1,1
3,2000,80,N,1,0,0
4,2500,120,Y,0,1,0
5,3500,110,N,0,0,1
6,6000,250,Y,1,1,0
7,4000,160,Y,1,1,1
8,2200,90,N,0,0,0
9,5800,210,Y,1,1,1
10,3300,130,Y,1,0,0
11,2700,100,N,0,1,0
12,3100,170,Y,1,1,1
13,2900,95,N,0,0,0
14,4600,180,Y,1,1,0
15,3200,115,N,0,0,1

In [78]:
Model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [80]:
Model.predict(x_test)

array([1, 0, 1, 0])